
DROP TABLE IF EXISTS `requests`;
CREATE TABLE IF NOT EXISTS `requests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `volunteer` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `shift_id` int(11) NOT NULL,
  `approved` varchar(40) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `shifts.id` (`shift_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE `requests`
  ADD CONSTRAINT `shifts.id` FOREIGN KEY (`shift_id`) REFERENCES `shifts` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
